CREATE DATABASE PHPAdvClassSpring2017 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE PHPAdvClassSpring2017;

CREATE TABLE IF NOT EXISTS phone (
phoneid INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
phone VARCHAR(12) NOT NULL UNIQUE KEY,
phonetype VARCHAR(50) NOT NULL,
logged DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00', 
lastupdated DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
active tinyint(1) UNSIGNED NOT NULL DEFAULT '1'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;